//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearchWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Security
    {
        public int Security_ID { get; set; }
        public int User_ID { get; set; }
        public int Cabinet_ID { get; set; }
        public int SecLevel_Cabinet { get; set; }
        public int SecLevel_Folder { get; set; }
        public int SecLevel_DocType { get; set; }
        public int SecLevel_Document { get; set; }
        public int LastUser_ID { get; set; }
        public System.DateTime LastUser_DT { get; set; }
    
        public virtual tbl_Cabinet tbl_Cabinet { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
