//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearchWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Config
    {
        public string FileServerDir { get; set; }
        public string UploadPath { get; set; }
        public string ErrorPath { get; set; }
        public string LogPath { get; set; }
        public long MaxLogSize { get; set; }
        public short LoggingLevel { get; set; }
        public short CheckingInterval { get; set; }
        public string EmailServer { get; set; }
        public string EmailRecipient { get; set; }
        public string EmailSender { get; set; }
        public string EmailNotification { get; set; }
        public short SqlCommandTimeout { get; set; }
        public short TimeoutErrorWait { get; set; }
        public short TimeoutErrorRetry { get; set; }
        public long MaxImageSize { get; set; }
        public short CheckConfigMinutes { get; set; }
    }
}
