//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearchWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocReference
    {
        public int DocReference_ID { get; set; }
        public int Document_ID { get; set; }
        public string RefNumber { get; set; }
        public string RefNumberType_CD { get; set; }
        public Nullable<System.DateTime> Date1_DT { get; set; }
        public Nullable<System.DateTime> Date2_DT { get; set; }
        public string Text1 { get; set; }
        public string Number1 { get; set; }
        public System.DateTime LastUser_DT { get; set; }
        public string Text2 { get; set; }
        public string Number2 { get; set; }
    
        public virtual tbl_Document tbl_Document { get; set; }
    }
}
