//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearchWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Repository
    {
        public int Repository_ID { get; set; }
        public int Cabinet_ID { get; set; }
        public string Name { get; set; }
        public string MainPath { get; set; }
        public short Sector { get; set; }
        public short Directory { get; set; }
        public short NextFileName { get; set; }
        public int LastUser_ID { get; set; }
        public System.DateTime LastUser_DT { get; set; }
    
        public virtual tbl_Cabinet tbl_Cabinet { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
