//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearchWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UpdatesData
    {
        public int Update_ID { get; set; }
        public string ColumnName { get; set; }
        public string OriginalData { get; set; }
        public string CurrentData { get; set; }
    
        public virtual tbl_Updates tbl_Updates { get; set; }
    }
}
